# Custom Language File for Launcher Customizer

[ejs.app]
title = "블널의 눈꽃마을"

[ejs.landing]
mediaGitHubURL = "https://github.com/jdhdfjs284/BlunelSnowVillage"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/drxQpTGjmB"
mediaSoopURL = "#"
mediaChzzkURL = "#"
screenshotsTooltip = "스크린샷"

[ejs.settings]
sourceGithubLink = "https://github.com/jdhdfjs284/BlunelSnowVillage"
supportLink = "https://github.com/jdhdfjs284/BlunelSnowVillage/issues"

[ejs.welcome]
welcomeHeader = "블널의 눈꽃마을"
welcomeDescription = ""
welcomeDescCTA = "계속하기 버튼을 눌러 계속 진행하여 주세요."